### ISSUE TITLE
ClassCastException in Tuning Thread - CRITICAL FAILURE

### ISSUE THREAD

**Issue by bdarfler** [whirlycott/Whirlycache#3]
```
2013-06-11 20:57:10,146 ERROR com.whirlycott.cache.CacheDecorator [Whirlycache Tuner ( xxxxx )] - Unexpected error in tuning thread... 
java.lang.ClassCastException: java.lang.String cannot be cast to com.whirlycott.cache.Cacheable
at com.whirlycott.cache.policy.LRUMaintenancePolicy.performMaintenance(Unknown Source) ~[whirlycache-2.0.jar:na]
at com.whirlycott.cache.CacheDecorator.run(Unknown Source) [whirlycache-2.0.jar:na]
at java.lang.Thread.run(Thread.java:662) [na:1.6.0_27]
```

**Comment by bdarfler** [comment]
Closing out my old issues.
