### ISSUE TITLE
Comparison method violates its general contract in Java 7 - CRITICAL ERROR

### ISSUE THREAD

**Issue by bdarfler** [whirlycott/Whirlycache#5]
```
2013-07-23 21:57:33,150 ERROR com.whirlycott.cache.CacheDecorator [Whirlycache Tuner ( cities )] - Unexpected error in tuning thread... 
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(TimSort.java:747) ~[na:1.7.0_21]
    at java.util.TimSort.mergeAt(TimSort.java:483) ~[na:1.7.0_21]
    at java.util.TimSort.mergeCollapse(TimSort.java:410) ~[na:1.7.0_21]
    at java.util.TimSort.sort(TimSort.java:214) ~[na:1.7.0_21]
    at java.util.TimSort.sort(TimSort.java:173) ~[na:1.7.0_21]
    at java.util.Arrays.sort(Arrays.java:659) ~[na:1.7.0_21]
    at java.util.Collections.sort(Collections.java:217) ~[na:1.7.0_21]
    at com.whirlycott.cache.policy.LRUMaintenancePolicy.performMaintenance(LRUMaintenancePolicy.java:66) ~[whirlycache-1.0.1.jar:na]
    at com.whirlycott.cache.CacheDecorator.run(CacheDecorator.java:358) ~[whirlycache-1.0.1.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
```

**Comment by nathsachindra** [comment]
We are seeing this error in our environments as well. This seems like a synchronization issue in whirlycott. com.whirlycott.cache.policy.LRUMaintenancePolicy.performMaintenance.
During expiry, it checks for the last used record counter on each item. It attempts to sort the values based on it, and remove the last used n items.
Since the sort is working on a shallow copy of the com.whirlycott.cache.Item instance, if another thread retrieved this item, and thus updated the last used, it will break the sort transitivity rule ( If A > B and B > C, then A > C) as the last used was concurrently updated.
This exception is a new addition in java 7 ( Java 6 would not report this as an issue). I believe this is harmless as the cache will be re-tuned at another attempt. The exception occurs in the cache tuning thread, which is a background thread, and should not cause a difference to user threads.

Do you however see a a possible fix without locking everything up?

**Comment by bdarfler** [comment]
Closing out my old issues.
